### ISSUE TITLE
Naming of resources seems wierd.

### ISSUE THREAD

**Issue by henrikbjorn** [mailjet/mailjet-apiv3-go#1]
Looking through some of the code i noticed that all of the resources are named `Apikeyaccess` with the first character capitalized and the rest lowercased. Most of the other Go code i have seen, even in the standard library would name this as `ApiKeyAccess` or `BatchJob`. It might be worth considering fixing this.

**Comment by arnaudbreton** [comment]
Hey @henrikbjorn,

In that first release we decided to stick to a capitalized only naming convention to facilitate the integration in the tool we built to generate code samples for our [API Guides](http://dev.mailjet.com/guides/?go#). 
We have planned to improve this in a future release. Sorry for the inconvenience.

Thanks for your feedback and your interest in Mailjet API!
Best,
Arnaud.

**Comment by henrikbjorn** [comment]
Hey @arnaudbreton 

But the same file also uses CamelCase aswell.

**Comment by GuillaumeBadi** [comment]
Hi @henrikbjorn !

Actually, the resources that are camelcase are the one that use some mailjet actions.
`contactslist/:id/managecontact` => `ContactslistManageContact`. 

We wanted to focus on uniformity in this first release and update the resources in future releases. So right now the names are formatted this way:

`ResourceAction`

Best,
Guillaume from Mailjet

**Comment by GuillaumeBadi** [comment]
Hi @henrikbjorn !

Actually you are right, there are still some irregularities that we need to fix in future releases. We use a code generator to build the structures. As arnaud said, we are going to improve it to fit CamelCase style for any API resource.

Best,
Guillaume from Mailjet!
