### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [mailjet/mailjet-apiv3-go#100]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Mailjet plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Mailjet data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by nlynch00** [comment]
Hey! Thank you for bringing this to us. It did end up in the right hands! I would love to take this offline and talk about it. Is there a way I can contact you or find you on LinkedIn? Let me know!

**Comment by yevgenypats** [comment]
Hey @nlynch00 Cool! Yeah ping me at `yp` at our domain (`cloudquery.io`).
