### ISSUE TITLE
Keep getting "connection reset by peer" error on Google cloud app engine

### ISSUE THREAD

**Issue by slash-dev** [mailjet/mailjet-apiv3-go#105]
Hi,

I've been using the Mailjet API for years and had no problem but since a few weeks, I started experiencing some "connection reset by peer" errors:

```
Error getting https://api.mailjet.com/v3/send/message: Post "https://api.mailjet.com/v3/send/message": read tcp 169.254.8.1:36658->35.187.79.8:443: read: connection reset by peer
```

I'm using Google cloud app engine.

I found a similar issue but it was because they were creating the client way before sending the email. Here I create a new client each time I try to send an email.

Is this expected?

Best,
Adrien

**Comment by EmanuelU** [comment]
We are having the exact same issue. As it is, we have to switch supplier because of this issue.

**Comment by wojtasiq** [comment]
We have the same issue in python library, retrying also doesn't help...

**Comment by EmanuelU** [comment]
It’s because Mailjet is blocking the GCP dynamic IPs seemingly randomly

**Comment by grekowski** [comment]
Same issue I'm facing using pure cURL. Described in [https://github.com/mailjet/mailjet-apiv3-php/issues/273](https://github.com/mailjet/mailjet-apiv3-php/issues/273)

**Comment by jhimy-michel** [comment]
I am having the same problem, I will go for another supplier as well.

**Comment by slash-dev** [comment]
Discussed with Mailjet support. They said that it's because they block some abusive IPs from GCP address range. They recommend to set up static IP address ([doc for app engine](https://cloud.google.com/appengine/docs/legacy/standard/python/outbound-ip-addresses)) which in my case defeats the whole purpose of using mailjet. If I set up a static IP address, I will use SMTP directly and add this IP to my SPF config.

**Comment by neilswingler** [comment]
I have a java app running in google app engine.  I hit this issue running in Europe West 1 (if the region makes a difference). I added a request to check and log my public ip address and it looks like for the life of a given instance the outgoing ip address is constant so I was able to identify a handful of ip addresses that Mailjet support has now unblocked. Otherwise I was having to kill _poisoned_ instances in the hope of getting a new instance with a usable external IPv4 address. Maybe IPv6 would solve this issue but the mailjet API does not offer an IPv6 address.

**Comment by glumb** [comment]
This is a severe topic, why do you block IPs and not API keys?
We need urgent help. Our customers are not receiving important email notifications because of this.

**Comment by jhimy-michel** [comment]
How I fixed is the following:
- I created a separate simple server in nodejs that scans a db table e.g. every minute
- this service is running in a server with fixed IP
- every my users requests an email sending, a new record is registered in the table
- and then my server to send emails process it, and remove the record after is done

If you know a better way to deal with this, please let me know.

**Comment by glumb** [comment]
Thanks @jhimy-michel for sharing. But I agree with @slash-dev , we use mailjet to send mails from our "serverless" infrastructure. 

Our "fix" will be to switch to a different provider if no solution can be found in a timely manner.

**Comment by glumb** [comment]
For everyone wondering how to solve this. We just switched to another provider, had no issues since. 😀

**Comment by vtopc** [comment]
I'm sorry to hear that, but it's not related to the SDK. 
If it's still an issue, please contact support at https://www.mailjet.com/contact/support/.
