### ISSUE TITLE
Unable to get details about an error (handling of 404)

### ISSUE THREAD

**Issue by mmjdotdk** [mailjet/mailjet-apiv3-go#111]
Since the contact lookup returns 404 when a contact is not found, it should be possible (besides string matching) to get access to details about the error. When using the package it's not possible to assert error into `RequestError`/`RequestError31` and look at the details.

**Comment by vtopc** [comment]
Hey. Which call are you using to do the contact lookup?

**Comment by vtopc** [comment]
So the next is not working, right?
```
import "errors"

...

	err := mjcli.Get(request, &contact)
	if err != nil {
		var mailjetErr mailjet.RequestError
		if errors.As(err, &mailjetErr) {
			fmt.Println(mailjetErr.StatusCode)
		}
	}
```

**Comment by mmjdotdk** [comment]
`errors: *target must be interface or implement error`

**Comment by mmjdotdk** [comment]
Using latest package from `go get github.com/mailjet/mailjet-apiv3-go` which seems to be `github.com/mailjet/mailjet-apiv3-go v0.0.0-20201009050126-c24bc15a9394`. This code here fails: (is the tests perhaps not showing the problem because their in the package itself, not a consumer of it)
```
func FindContactIdByEmail(email string) (int64, error) {
        mjcli := mailjet.NewMailjetClient(os.Getenv("MAILJET_PUBLIC_KEY"), os.Getenv("MAILJET_SECRET_KEY"))
        request := &mailjet.Request{
                Resource: "contact",
                AltID:    email,
        }
        var contact []resources.Contact

        err := mjcli.Get(request, &contact)
        var mjErr mailjet.RequestError
        if err != nil {
                if errors.As(err, &mjErr) {
                        if mjErr.StatusCode == 404 {
                                fmt.Printf("Contact not found for email %s\n", email)
                                return 0, nil
                        }
                }
                panic(err)
        }

        return contact[0].ID, nil
}
```

**Comment by vtopc** [comment]
> Seems I was using the wrong version -- adding `/v4/` fixed it. May I suggest you update the official examples to reflect this. There's is no mention of `v4` in the Go example here: https://dev.mailjet.com/email/guides/contact-management/.

It's in the README - https://github.com/mailjet/mailjet-apiv3-go?tab=readme-ov-file#installation

**Comment by mmjdotdk** [comment]
Yes, that's where I found it. But the Golang examples on the API documentation on mailjets own site is wrong.

**Comment by vtopc** [comment]
> Seems I was using the wrong version -- adding `/v4/` fixed it. May I suggest you update the official examples to reflect this. There's is no mention of `v4` in the Go example here: https://dev.mailjet.com/email/guides/contact-management/.

Check https://github.com/mailjet/api-documentation/blob/master/guides/_contacts_bulk.md
it's Mailjet...
