### ISSUE TITLE
SentResult - shouldn't MessageID be int64 ?

### ISSUE THREAD

**Issue by DaveAppleton** [mailjet/mailjet-apiv3-go#22]
I am getting 
`cannot unmarshal number 18858926273619457 into Go value of type int`

in mailjet_resources.go : 

```
// SentResult is the JSON result sent by the Send API.
type SentResult struct {
	Sent []struct {
		Email     string
		MessageID int
	}
}
```

**Comment by Zhivko-Mailjet** [comment]
Hi @DaveAppleton ,

Thanks for reporting this. Value of messageID should be now of type int64.
