### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by colesimmons** [mailjet/mailjet-apiv3-go#37]
The code example at https://dev.mailjet.com/guides/#using-a-template suggests using struct literals `MJTemplateID` and `MJTemplateLanguage` - which both returned "unknown field" errors.

I found in [mailjet_resources.go](https://github.com/mailjet/mailjet-apiv3-go/blob/206edd5616d0ea56b815ecc0a40250dd64c6eff3/mailjet_resources.go) that these are defined instead as `MjTemplateID` and `MjTemplateLanguage`.

Furthermore, in the code example, `MJTemplateID` takes an int, but `MjTemplateID` takes a string.

That is the only section of guide I have looked at, but I suspect similar errors are scattered throughout.

**Comment by Zhivko-Mailjet** [comment]
@colesimmons 
Thanks for your feedback! We will go through the documentation and adjust the samples to match the properties in the wrapper. Thanks again for spotting and reporitng this!

**Comment by Zhivko-Mailjet** [comment]
@colesimmons 
I just wanted to let you know that the issue has been addressed. Thanks again for reporting the problem!

**Comment by colesimmons** [comment]
Thanks! It's been a joy to use!

**Comment by arnaudbreton** [comment]
@colesimmons thanks for the feedback, glad you like it!
