### ISSUE TITLE
Mocking example

### ISSUE THREAD

**Issue by gyurobenjamin** [mailjet/mailjet-apiv3-go#44]
Is there any example how to mock the client?

**Comment by maxchampoux** [comment]
Hey Benjamin,
You may find examples in the `example_test.go` which is pretty exhaustive: https://github.com/mailjet/mailjet-apiv3-go/blob/master/example_test.go
Alternatively, mocks can be found here: https://github.com/mailjet/mailjet-apiv3-go/blob/master/http_client_mock.go
Looking forward hearing from you,
Best
Maxime

**Comment by abambova** [comment]
Hi @gyurobenjamin ,
I'll close the issue as the examples are provided. Please feel free to open a new issue, if needed.
