### ISSUE TITLE
stream error: stream ID 1; PROTOCOL_ERROR

### ISSUE THREAD

**Issue by benlind** [mailjet/mailjet-apiv3-go#58]
Today (at 13:53 ET) we sent a request to https://api.us.mailjet.com/v3.1/send via `SendMailV31` and received this error response:

```
Post https://api.us.mailjet.com/v3.1/send: stream error: stream ID 1; PROTOCOL_ERROR
```

Our sending code:

```go
messages := mailjet.MessagesV31{Info: messagesInfo}
_, err := mailjetClient.SendMailV31(&messages)
if err != nil {
  switch v := err.(type) {
  // ...
  default:
    errorMsg := fmt.Sprintf("got unexpected MailJet error (type %T): %s", v, err)
    return errors.New(errorMsg), false
  }
}
```

Looking around the net, looks like that could be caused by [newlines in a stream](https://github.com/grpc/grpc-go/issues/576).

**Comment by bmbmjmdm** [comment]
+1

**Comment by tsidei** [comment]
the actual versions of `grpc/grpc-go` contains a fix for that issue so it should not appear again. Let us know if you bump into this again.
