### ISSUE TITLE
Sender resource always gets empty DNS

### ISSUE THREAD

**Issue by tolik505** [mailjet/mailjet-apiv3-go#61]
I'm trying to fetch a sender
```
        var data []resources.Sender
	mr := &mailjet.Request{
		Resource: "sender",
		ID:       int64(18642),
	}
	err := mjClient.Get(mr, &data)
```
And I get empty data[0].DNS despite the DNS is visible when I'm using Postman, but the field is called DNSID there.
The problem might be in unmarshaling of json response since DNS field in a struct doesn't match DNSID field in json.

**Comment by tsidei** [comment]
this is fixed in #66 . You can use the `DNSID` field now.
