### ISSUE TITLE
Errors in the example code on first mailjet login

### ISSUE THREAD

**Issue by juumixx** [mailjet/mailjet-apiv3-go#71]
When logging into mailjet for the first time and selecting "Developer", you get a simplified version of the Go API example with the following errors:
1. the "os" import is unused (the env variables are replaced with prefilled tokens there)
2. the NewMailjetClient call can't be resolved without namespace
3. the pre-filled API key strings use ' instead of " which results in a type error
4. the m.SendMailV31 call can't be resolved (m is undefined)

**Comment by tsidei** [comment]
unfortunately that example is not under our team's control and we can't fix it by ourselves. But we made sure the responsible team got the details and it'll be fixed as soon as they get there. 

Meanwhile, anyone bumping into this can use the examples from our README. We've checked and fixed them all so please use them for now.
