### ISSUE TITLE
Type resources.ContactGetcontactslists doesn't exists

### ISSUE THREAD

**Issue by scorsi** [mailjet/mailjet-apiv3-go#74]
Hello,

Actually there's no typing when requesting `GET /contact/{contact_ID}/getcontactslists` (`resources.ContactGetcontactslists` doesn't exists). Can it be added ? 

The type is:
```go
type ContactGetcontactslists struct {
    ListID       int64  `json:"ListID"`
    IsUnsub      bool   `json:"IsUnsub"`
    SubscribedAt string `json:"SubscribedAt"`
}
```

Thanks,

**Comment by tsidei** [comment]
sure, will be added once #75 is merged. Thanks for reporting.
