### ISSUE TITLE
type MailjetSendMail

### ISSUE THREAD

**Issue by didierparisot** [mailjet/mailjet-apiv3-go#8]
Bonjour

nous sommes clients Mailjet (CAPITALDATA)

j'ai une question concernant le type MailjetSendMail

j'avais créé un package mailjet qui me permettait de paramétrer les variables 'mj-deduplicatecampaign' et 'mj-campaign' (ma question porte sur ces 2 variables)

je souhaite maintenant utiliser le vôtre

### 1/ Concernant :  'mj-deduplicatecampaign'

dans http://dev.mailjet.com/guides/?go#grouping-into-a-campaign

il est donnée en exemple : 
    email := &MailjetSendMail {
      FromEmail: "pilot@mailjet.com",
      FromName: "Mailjet Pilot",
      Subject: "Your email flight plan!",
      TextPart: "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
      HtmlPart: "...",
      Recipients: []MailjetRecipient {
        MailjetRecipient {
          Email: "passenger@mailjet.com",
        },
      },
      MjCampaign: "SendAPI_campaign",
      **MjDeduplicatecampaign**: 1,
    }

Mais lorsque je compile (NB : je suis en go1.5) j'obtiens l'erreur 
*' unknown mailjet.MailjetSendMail field 'MjDeduplicatecampaign' in struct literal'*

Pourriez vous me donner le bon nom du champ, ou bien m'indiquer où je peux trouver l'instanciation du type dans le package (pas trouvé) ?

#### 2/ Concernant :  'mj-campaign'

Confirmez vous que dans ce même type il s'agit du field 'MjCampaign' ?

Merci beaucoup par avance pour vos réponses

Didier Parisot

**Comment by kgilonne** [comment]
Bonsoir @didierparisot ,

Merci d'avoir remonté cette typo.
Le nom exact du champ est 'MjDeduplicateCampaign' et non 'MjDeduplicatecampaign',
pour le second il s'agit effectivement du champ 'MjCampaign'.
cf. https://github.com/mailjet/mailjet-apiv3-go/blob/master/mailjet_resources.go#L81

En espérant couvrir vos attentes,
Kilian.

**Comment by didierparisot** [comment]
bonjour
merci pour votre retour
cela fonctionne
merci
dP
