### ISSUE TITLE
No way for callers to cancel or set deadlines through Context

### ISSUE THREAD

**Issue by cbjartli** [mailjet/mailjet-apiv3-go#85]
Currently, the Mailjet Client does not support cancellation or deadlines through context.Context.

Similar libraries often have this feature, e.g. [sendgrid-go](https://github.com/sendgrid/sendgrid-go), which supports SendWithContext and similar methods.

I have supplied a pull request which should provide a backwards compatible/non-breaking implementation [here](https://github.com/mailjet/mailjet-apiv3-go/pull/84).

**Comment by tsidei** [comment]
now it's possible with all methods in the latest release by using the `RequestOptions`
