### ISSUE TITLE
Post "https://api.mailjet.com/v3.1/send": connection error: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by nam-truong-le** [mailjet/mailjet-apiv3-go#94]
I'm getting this error. Would you mind checking it? With some retires, it works.

**Comment by bogdanprodanj** [comment]
Could you please provide a code snippet so I can try to reproduce this error?

**Comment by nam-truong-le** [comment]
This happens very rarely, I added a retry mechanism to my code and since then it works (still the first attempt fails rarely).

**Comment by kgilonne** [comment]
Hello @nam-truong-le, this kind of error happen when using a HTTP2 connection (https://pkg.go.dev/golang.org/x/net/http2) and stream is reset or simply failing.
https://github.com/golang/go/issues/29125
https://github.com/golang/go/issues/31534

A retry mechanism is always recommended whatever the endpoint your are calling 👍
Simply ensure that you are not retrying on fatal errors.

**Comment by kgilonne** [comment]
I just noticed how old is this issue, will close 🙏
