### ISSUE TITLE
Please provide a mechanism to use a custom http.Client

### ISSUE THREAD

**Issue by nam-truong-le** [mailjet/mailjet-apiv3-go#95]
Currently the http.DefaultClient is used.

```go
// NewHTTPClient returns a new httpClient
func NewHTTPClient(apiKeyPublic, apiKeyPrivate string) *HTTPClient {
	return &HTTPClient{
		apiKeyPublic:  apiKeyPublic,
		apiKeyPrivate: apiKeyPrivate,
		client:        http.DefaultClient,
	}
}
```

Changing the http.DefaultClient might affect other libs. It will be nice if it's possible to provide custom http.Client.

**Comment by vtopc** [comment]
What about [(*HTTPClient) SetClient(client *http.Client)](https://github.com/mailjet/mailjet-apiv3-go/blob/4a03c376ccaa885bd30f3255448173a1b8ae96df/http_client.go#L45)?

**Comment by nam-truong-le** [comment]
Thank you. I missed this information.
