### ISSUE TITLE
The status variable of Campaign should be an Integer

### ISSUE THREAD

**Issue by c-louis** [mailjet/mailjet-apiv3-go#98]
Hi, I'm having a little issue using this module.

As mentioned in the documentation : 
https://dev.mailjet.com/email/reference/campaigns/sent-campaigns#v3_get_campaign

The Status variable is supposed to be an Integer.

But in the module : 
https://github.com/mailjet/mailjet-apiv3-go/blob/4a03c376ccaa885bd30f3255448173a1b8ae96df/resources/resources.go#L199

It creates an error : 
[00] Error decoding API response: json: cannot unmarshal number into Go struct field Campaign.Data.Status of type string

**Comment by teros0** [comment]
Good catch, merged a fix.
